### ISSUE TITLE
남은 작업들 톺아보기

### ISSUE THREAD

**Issue by pongsoyun** [pongsoyun/TheBible#35]
## Done
- [x] 치유하고 화아… 넣기… 
- [x] 하늘 두배 더 느리게
- [x] 조작법 없애기
- [x] 말풍선 2개 더 넣기 Cpt House ! ( 구해줘야겠다 생각하는 부분, 수근수근이수근)
- [x] 말풍선 메인 추가하기 ( 마지막에 작토끼, 큰토끼 수근수근)
- [x] Cpt house 마지막 부분 Cure -> cure
- [x] 캡틴 집 다녀와서 말풍선 작은토끼에서만 나오고 큰토끼에서 안나옴
- [x] 언덕 collider
- [x] 사운드 넣기
- [x] 바구니 해결
- [x] 이동할 때 카메라 움직이지 않도록 하기
- [x] 토끼 고마워 점프점프 애니메이션 + 사운드 처리 @pongsoyun 
- [x] Monster 리소스 변경 -> Town, Screen 수정
- [x] CM collider 영역 늘려놓기 @pongsoyun 
- [x] 파티클 입자 변경 @pongsoyun 
- [x] 클로징 멘트 넣을수있게 처리
- [x] 아픈 토끼 애니메이션 말풍선 끝나기전에는 아픈 상태로 뒤에 붙는 것 Hint : isPlayed
- [x] 엔딩크레딧 -> VCAM 싣고 크레딧에 쓸 내용 적으면 될듯
- [x] 따라다니는 토끼(Pet) 마을 초입에서 우로 총총총하고 가는거 처리
- [x] 좌우에서 돌던지면서 다가오는 토끼들 위치 맞추기
- [x] 로딩화면 이미지(튜토리얼) 변경(디자이너 리소스주면넣기) 
- [x] 초반 몇초후에 나타나는거+좌우에서오는거
## To Do
- [x] CM Collider 점프나 기타 이슈로 충돌 인지 못할 경우
- [x] E버튼에 Event 없을때도 사운드 출력
- [x] 미니게임 clear? 

## 엔딩 관련
- [x] 시네머신 시야 처리 -> 검은 바 점점 내려오게(Alpha값 살짝 줘서 흐리게) 가운데영역

**Comment by YeonduBori** [comment]
@pongsoyun 아픈 토끼 상태로 뒤에 붙는 걸 해결하기위해 isPet이더라도 아픈 애니메이션 재생중엔 안 따라갑니다 ->
 이후 폴짝폴짝 뛸 때 순간이동이 아니라 플레이어 뒤로 따라붙도록 조정했습니다 ->
 그 이후에 따라다니도록 조정했습니다.

**Comment by YeonduBori** [comment]
@pongsoyun 언덕 낑기는 문제 해결했습니다.

**Comment by pongsoyun** [comment]
- `isPlayed` 관련해서 토끼마을 입성 후에 movie, 삥뜯기 당하는 부분 확인부탁드립니당
- 마을 초입에서 꺼야하는데 SickRabbit 충돌인식이 안됩니다 ㅜㅜ.. 주석달아놨는데 호옥시 한번 봐주실수있을까여 😭

**Comment by pongsoyun** [comment]
엔딩크레딧은 완료했고, 영화에서 보듯이 위에서 아래로 스크롤 하는 형식으로 하려다가 다시 하늘로 올라가는 느낌 -> 수미상관 을 낭낭! 하게 주기 위해 아래~위로 그대로 구현하였습니다~! 참고 부탁드려욧 ! (vcam 하나 추가해서 마지막 코멘트 보여주고, 씀) 

그리고 애니메이션 잘리는 현상이나, 카메라들도 손봤습니다! 풀땡겨오셔서 한번 플레이 고고 하시면 될것같아욧!! 

수고많으셨습니다 오늘하루 치얼스- 🤳🏻

**Comment by pongsoyun** [comment]
위 해당 이슈들 모두 해결 ! 이제 로딩만 넣으면 정말 `완성`이네요! 수고많으셨습니다~! :tada:

**Comment by pongsoyun** [comment]
플레이하면서 수정해야할 추가 이슈는 #36
