### ISSUE TITLE
Build된 게임 BugFix/issues List

### ISSUE THREAD

**Issue by pongsoyun** [pongsoyun/TheBible#38]
자 이제부터 열심히 게임을하면서, `bugFix`가 필요하거나 수정되어야할부분들을 적어나갑니다

**Comment by pongsoyun** [comment]
- [x] gameOverSound 안나오는 부분 처리
- [x] cliff 부분 땅 유격조금있는거 처리
- [x] 토끼 바구니보다 앞으로나오는 부분 처리

@JisungParkk 빌드버전에서 바뀐부분이에요! 이거 제외하고 플레이하면서 리소스나 수정되어야하는부분/ 이슈발견시 적어주세요 !

**Comment by JisungParkk** [comment]
- [ ] 미니게임 로딩 화면에 그 미니게임에 맞지 않는 곳에 들어가는 것 같아요! 왕토끼 집에 들어갈 때에도 미니게임 로딩이 나옵니다!

- [ ] 미니게임 2를 해본 후, 그냥 날아가는 돌을 클릭만 하면 되니 뭔가 단조로운 것 같아서 남은 시간을 보여주면 어떨까 싶습니다!

**Comment by YeonduBori** [comment]
@pongsoyun @JisungParkk  미니게임 로딩 나오는 이유는 넘어갈때 몇번 인덱스 사진 출력할지 정해진게 기본이라 캡틴 넘어갈때 사진 뭐 넣을지 결정해주세요

**Comment by YeonduBori** [comment]
@JisungParkk @pongsoyun 몇 개 남았는지 표시해주는건 미니게임 1,2 다 적용해야겠네요 남은 시간은 없고 몇 개를 없애냐가 기준입니다 :)

**Comment by pongsoyun** [comment]
![image](https://user-images.githubusercontent.com/47388920/82042708-5242ad00-96e5-11ea-80a9-f3af5b0c5b78.png)
위치조절..

**Comment by pongsoyun** [comment]
최종 !@##!@!@# 진짜 최종 !@#!@# 끝 !@#!@!#@ 

수고하셨습니다 💓 :tada:
